GH action with sonar-scanner (#647)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,11 @@
 name: BUILD
 
-on: [push, pull_request, workflow_dispatch]
+on:
+  push:
+    branches:
+      - master
+  pull_request:
+  workflow_dispatch:
 
 jobs:
 
@@ -8,6 +13,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+        with:
+          # Disabling shallow clone is recommended for improving relevancy of reporting for sonar
+          fetch-depth: 0
 
       - name: Cache local Maven repository
         uses: actions/cache@v2
@@ -23,6 +31,60 @@ jobs:
         with:
           distribution: 'zulu'
           java-version: '11'
+
+      - name: Setup Sonar Scanner
+        uses: warchant/setup-sonar-scanner@v3
+        with:
+          version: 4.6.2.2472
+
+      - name: Run Sonar Scanner
+        env:
+          # provide GITHUB_TOKEN to get access to secrets.SONAR_TOKEN
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        working-directory: code
+        run: |
+          export JAVA_OPTS="-Xms6g -Xmx6g"
+          export ES_JAVA_OPTS="-Xms6g -Xmx6g"
+          sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
+
+      - name: Get list of tests
+        if: always()
+        id: tests
+        uses: Rishabh510/Path-lister-action@master
+        with:
+          path: "code/test-reports"
+          type: ".xml"
+
+      - name: Fail on failed tests
+        if: always()
+        run: |
+          sudo apt-get install -y libxml2-utils
+          echo "Found ${{ steps.tests.outputs.path_count }} test report(s)"
+          if [[ ${{ steps.tests.outputs.path_count }} < 1 ]]; then
+             echo "ERROR: No unit test reports collected."
+             exit 1
+          fi
+          for f in ${{ steps.tests.outputs.paths }}; do
+            echo "=== $f ==="
+            if [[ $(xmllint --xpath "string(//testsuite/@failures)" $f) > 1 ]]; then
+               echo TEST FAILED: $f
+               exit 1
+            fi
+            if [[ $(xmllint --xpath "string(//testsuite/@errors)" $f) > 1 ]]; then
+               echo TEST ERRORED: $f
+               exit 1
+            fi
+          done
+
+      - name: SonarQube Quality Gate check
+        uses: sonarsource/sonarqube-quality-gate-action@v1.0.0
+        # Force to fail step after specific time
+        timeout-minutes: 5
+        with:
+          scanMetadataReportFile: code/.scannerwork/report-task.txt
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
       - uses: s4u/maven-settings-action@v2.2.0
         with:
@@ -49,7 +111,13 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           SIXSQ_DOCKER_USERNAME: ${{ secrets.SIXSQ_DOCKER_USERNAME }}
           SIXSQ_DOCKER_PASSWORD: ${{ secrets.SIXSQ_DOCKER_PASSWORD }}
-        run: mvn deploy
+        run: mvn deploy -DskipTests=true
+
+      - name: Publish Unit Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v1
+        if: always()
+        with:
+          files: code/test-reports/TEST-*.xml
 
   job-notify:
     if: always()
